config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'catalog#index'
  get 'catalog' => 'catalog#index'
  resources :users_subs_relationships, only: [:new, :create, :edit, :update]
  resources :orders, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  validates :user_id, presence: true
  belongs_to :user

  has_one :package
end

app/models/package.rb
class Package < ApplicationRecord
  validates :order_id, presence: true
  belongs_to :order

  has_many :pastas_packages_relationships
  has_many :pastas, through: :pastas_packages_relationships
end

app/models/pasta.rb
class Pasta < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :pastas_packages_relationships
  has_many :packages, through: :pastas_packages_relationships
end

app/models/pastas_packages_relationship.rb
class PastasPackagesRelationship < ApplicationRecord
  validates :pasta_id, presence: true
  validates :package_id, presence: true
  belongs_to :pasta
  belongs_to :package
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :monthly_price, presence: true, numericality: { only_integer: true, greater_than: 0 }
  has_many :users_subs_relationships
  has_many :users, through: :users_subs_relationships

  def pasta_count_allowed
    return 2 if self.monthly_price == 15
    return 4 if self.monthly_price == 25
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :users_subs_relationship
  has_one :subscription, through: :users_subs_relationship

  has_many :orders

  def can_still_add_pasta?(last_order)
    last_order.package.pastas.count < self.subscription.pasta_count_allowed
  end
end

app/models/users_subs_relationship.rb
class UsersSubsRelationship < ApplicationRecord
  validates :user_id, presence: true
  validates :subscription_id, presence: true
  belongs_to :user
  belongs_to :subscription
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from ActiveRecord::RecordNotFound, :with => :not_found

  # redirect to subscription form after sign in
  def after_sign_in_path_for(resource_or_scope)
    return new_users_subs_relationship_url unless current_user.subscription
    root_path
  end

  def not_found(e)
    render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found
  end

end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController

  def index
    @pastas = Pasta.all
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authenticate_user!

  def index
    @orders = current_user.orders
  end

  def create
    last_order = current_user.orders.last
    success_message = 'Thanks for your order :)'
    if last_order && current_user.can_still_add_pasta?(last_order)
      last_order.package.pastas_packages_relationships.create(pasta_id: params[:pasta_id])
      flash[:notice] = success_message
    else
      new_order = Order.new(user: current_user)
      if new_order.save
        package = new_order.create_package(order_id: new_order.id)
        package.pastas_packages_relationships.create(pasta_id: params[:pasta_id], package_id: package.id)
        flash[:notice] = success_message
      else
        Order.destroy(order.id)
        flash[:alert] = 'Something went wrong :('
      end
    end
    redirect_to root_path
  end



end

app/controllers/users_subs_relationships_controller.rb
class UsersSubsRelationshipsController < ApplicationController

  before_action :set_user_subs_relationship, only: [:edit, :update]
  before_action :authenticate_user!
  before_action :require_to_have_no_subscription, only: [:new, :create]

  def new
    @users_subs_relationship = UsersSubsRelationship.new
  end

  def create
    @users_subs_relationship = UsersSubsRelationship.create(users_subs_relationship_params.merge(user: current_user))
    if @users_subs_relationship.valid?
      flash[:notice] = 'Thanks for choosing your plan :)'
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    last_order = current_user.orders.last
    if last_order && current_user.can_still_add_pasta?(last_order)
      flash[:alert] = "You can't change plan now because pastas are missing on your last order"
      redirect_to root_path
    else
      @users_subs_relationship.update_attributes(users_subs_relationship_params)
      if @users_subs_relationship.valid?
        flash[:notice] = 'Your plan has been updated'
        redirect_to root_path
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  private
    def users_subs_relationship_params
      params.require(:users_subs_relationship).permit(:subscription_id)
    end

    def set_user_subs_relationship
      @users_subs_relationship = UsersSubsRelationship.find(params[:id])
    end

    def require_to_have_no_subscription
      if current_user.subscription
        flash[:notice] = 'You already have a subscription'
        redirect_to root_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_subs_relationships_helper.rb
module UsersSubsRelationshipsHelper
end

app/views/catalog/index.html.erb
<br/><h5 class="">Pastas list</h5><br/>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @pastas.each do |pasta| %>
      <tr>
        <td><%= pasta.name %></td>
        <td>
          <%= form_tag('/orders') do %>
            <%= hidden_field_tag 'pasta_id', pasta.id  %>
            <%= submit_tag 'Order', class: 'btn btn-outline-info btn-sm' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fresh Pasta Plan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #364051;">
      <a class="text-white navbar-brand" href="<%= root_path %>">Fresh Pasta Plan</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="text-white nav-link" href="<%= root_path %>">Catalog</a>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="text-white nav-link" href="<%= orders_path %>">My Orders</a>
            </li>
          <% end %>
          <% if user_signed_in? && current_user.users_subs_relationship != nil %>
            <li class="nav-item">
              <a class="text-white nav-link" href="<%= edit_users_subs_relationship_path(current_user.users_subs_relationship) %>">Change my plan</a>
            </li>
          <% end %>
        </ul>

        <% if user_signed_in? %>
          <%= link_to t('.sign_out'), destroy_user_session_path, method: :delete,
            class: 'text-white nav-link' %>
        <% else %>
          <%= link_to t('.sign_in'), new_user_session_path, class: 'text-white nav-link' %>
          <%= link_to t('.sign_up'), new_user_registration_path, class: 'text-white nav-link' %>
        <% end %>

      </div>
    </nav>

    <div class="background">
      <div class="container">
        <div class="row">
          <div class="col-sm">
            <% if notice.present? %>
              </br><div class="p-3 mb-2 bg-success text-white rounded"><%= notice %></div>
            <% end %>
          	<% if alert.present? %>
              </br><div class="p-3 mb-2 bg-danger text-white rounded"><%= alert %></div>
          	<% end %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<br/><h5 class="">My orders</h5><br/>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Package</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td>
          <% order.package.pastas.each do |pasta| %>
            <p><%= pasta.name %><p>
          <% end %>
        </td>
        <td>No action yet</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users_subs_relationships/_form.html.erb
</br>
<%= simple_form_for(@users_subs_relationship) do |f| %>
  <%= f.collection_select :subscription_id, Subscription.all, :id, :name %></br>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<script type="text/javascript">
  $("select").addClass("form-control");
</script>

app/views/users_subs_relationships/edit.html.erb
</br>Edit your plan</br>
<%= render 'form', users_subs_relationship: @users_subs_relationship %>

app/views/users_subs_relationships/new.html.erb
</br>Choose your plan</br>
<%= render 'form', users_subs_relationship: @users_subs_relationship %>